#!/usr/bin/env bun
import { writeFile, mkdir } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const DEFAULT_SOURCE = 'https://api.mynextadventure.cloud/v1/openapi.json'
const REPO_ROOT = resolve(import.meta.dir, '..')
const OUT_PATH = resolve(REPO_ROOT, 'src/api/generated/schema.ts')
const SNAPSHOT_PATH = resolve(REPO_ROOT, 'openapi.json')

async function generateFrom(source: string): Promise<string> {
    const ast = await openapiTS(new URL(source))
    return astToString(ast)
}

async function main() {
    const explicit = process.env.MNA_OPENAPI_URL
    // Prefer the committed local snapshot first, then fall back to the live
    // production URL. The snapshot is the source of truth committed alongside
    // server changes, so CI lands green regardless of deploy timing; the URL
    // fallback covers a fresh checkout where the snapshot file might be
    // missing or someone wants to force-pull the latest prod surface.
    const sources = explicit
        ? [explicit]
        : [pathToFileURL(SNAPSHOT_PATH).toString(), DEFAULT_SOURCE]

    let contents: string | undefined
    let usedSource: string | undefined
    let lastError: unknown
    for (const source of sources) {
        try {
            console.log(`Generating types from: ${source}`)
            contents = await generateFrom(source)
            usedSource = source
            break
        } catch (err) {
            lastError = err
            const msg = (err as Error)?.message ?? String(err)
            console.warn(`  ${msg}`)
            if (sources.indexOf(source) < sources.length - 1) {
                console.warn('  Falling back to next source...')
            }
        }
    }

    if (!contents || !usedSource) {
        throw lastError ?? new Error('No OpenAPI source produced types.')
    }

    const header = [
        '// AUTO-GENERATED by `bun run codegen` — do not edit by hand.',
        `// Source: ${usedSource}`,
        `// Generated: ${new Date().toISOString()}`,
        '',
        '',
    ].join('\n')

    await mkdir(dirname(OUT_PATH), { recursive: true })
    await writeFile(OUT_PATH, header + contents, 'utf8')

    console.log(`Wrote ${OUT_PATH}`)
}

main().catch((err) => {
    console.error('Codegen failed:', err.message ?? err)
    process.exit(1)
})
