#!/usr/bin/env bun
import { writeFile, mkdir } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

const DEFAULT_SOURCE = 'https://mynextadventure.com/v1/openapi.json'
const OUT_PATH = resolve(import.meta.dir, '../src/api/generated/schema.ts')

async function main() {
    const source = process.env.MNA_OPENAPI_URL ?? DEFAULT_SOURCE
    console.log(`Generating types from: ${source}`)

    const ast = await openapiTS(new URL(source))
    const contents = astToString(ast)

    const header = [
        '// AUTO-GENERATED by `bun run codegen` — do not edit by hand.',
        `// Source: ${source}`,
        `// Generated: ${new Date().toISOString()}`,
        '',
        '',
    ].join('\n')

    await mkdir(dirname(OUT_PATH), { recursive: true })
    await writeFile(OUT_PATH, header + contents, 'utf8')

    console.log(`Wrote ${OUT_PATH}`)
}

main().catch((err) => {
    console.error('Codegen failed:', err.message ?? err)
    process.exit(1)
})
